# ----------------------- #
#      Main Configs       #
# ----------------------- #
# base
url:            https://maehachi08.github.io
baseurl:        ""
title:          "maehachi08 Anything Blog"
subtitle:       "Soon there"
author:         Kazunori Maehata(@maehachi08)
description:    "Tech..."
timezone:       Asia/Tokyo

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
